// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * CommonSection frpc [common] 配置节
 * 参考: https://gofrp.org/zh-cn/docs/client-config/
 */
export class CommonSection {
    /**
     * Creates a new CommonSection instance.
     * @param {Partial<CommonSection>} [$$source = {}] - The source object to create the CommonSection.
     */
    constructor($$source = {}) {
        if (!("serverAddr" in $$source)) {
            /**
             * 服务器配置
             * @member
             * @type {string}
             */
            this["serverAddr"] = "";
        }
        if (!("serverPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["serverPort"] = 0;
        }
        if (!("authToken" in $$source)) {
            /**
             * 认证配置
             * @member
             * @type {string}
             */
            this["authToken"] = "";
        }
        if (!("authMethod" in $$source)) {
            /**
             * token, oidc
             * @member
             * @type {string}
             */
            this["authMethod"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * 用户名，用于区分不同客户端
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * 传输配置
             * tcp, kcp, websocket, wss, quic
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("tlsEnable" in $$source)) {
            /**
             * 启用 TLS
             * @member
             * @type {boolean}
             */
            this["tlsEnable"] = false;
        }
        if (!("serverName" in $$source)) {
            /**
             * TLS Server Name，用于证书验证
             * @member
             * @type {string}
             */
            this["serverName"] = "";
        }
        if (!("heartbeatInterval" in $$source)) {
            /**
             * 心跳配置
             * 心跳间隔（秒）
             * @member
             * @type {number}
             */
            this["heartbeatInterval"] = 0;
        }
        if (!("heartbeatTimeout" in $$source)) {
            /**
             * 心跳超时（秒）
             * @member
             * @type {number}
             */
            this["heartbeatTimeout"] = 0;
        }
        if (!("adminAddr" in $$source)) {
            /**
             * Dashboard 配置（用于获取代理状态和流量）
             * Dashboard 地址，默认使用服务器地址
             * @member
             * @type {string}
             */
            this["adminAddr"] = "";
        }
        if (!("adminPort" in $$source)) {
            /**
             * Dashboard 端口，默认 7500
             * @member
             * @type {number}
             */
            this["adminPort"] = 0;
        }
        if (!("adminUser" in $$source)) {
            /**
             * Dashboard 用户名（可选）
             * @member
             * @type {string}
             */
            this["adminUser"] = "";
        }
        if (!("adminPassword" in $$source)) {
            /**
             * Dashboard 密码（可选）
             * @member
             * @type {string}
             */
            this["adminPassword"] = "";
        }
        if (!("subDomainHost" in $$source)) {
            /**
             * HTTP 代理访问配置（可选）
             * 子域名后缀，如 frp.example.com，用于构建完整访问链接
             * @member
             * @type {string}
             */
            this["subDomainHost"] = "";
        }
        if (!("httpPort" in $$source)) {
            /**
             * HTTP 访问端口，默认 80
             * @member
             * @type {number}
             */
            this["httpPort"] = 0;
        }
        if (!("httpsPort" in $$source)) {
            /**
             * HTTPS 访问端口，默认 443
             * @member
             * @type {number}
             */
            this["httpsPort"] = 0;
        }
        if (!("transport" in $$source)) {
            /**
             * 其他配置
             * @member
             * @type {{"proxyUrl": string}}
             */
            this["transport"] = {"proxyUrl": ""};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommonSection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommonSection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommonSection(/** @type {Partial<CommonSection>} */($$parsedSource));
    }
}

/**
 * ConfigMeta 配置文件元数据
 */
export class ConfigMeta {
    /**
     * Creates a new ConfigMeta instance.
     * @param {Partial<ConfigMeta>} [$$source = {}] - The source object to create the ConfigMeta.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("autoStartOnLaunch" in $$source)) {
            /**
             * 程序启动时自动启动此配置
             * @member
             * @type {boolean}
             */
            this["autoStartOnLaunch"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigMeta}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new ConfigMeta(/** @type {Partial<ConfigMeta>} */($$parsedSource));
    }
}

/**
 * FrpcConfig frpc 配置文件结构
 */
export class FrpcConfig {
    /**
     * Creates a new FrpcConfig instance.
     * @param {Partial<FrpcConfig>} [$$source = {}] - The source object to create the FrpcConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("common" in $$source)) {
            /**
             * @member
             * @type {CommonSection | null}
             */
            this["common"] = null;
        }
        if (!("proxies" in $$source)) {
            /**
             * @member
             * @type {ProxyConfig[]}
             */
            this["proxies"] = [];
        }
        if (!("autoStartOnLaunch" in $$source)) {
            /**
             * 程序启动时自动启动此配置
             * @member
             * @type {boolean}
             */
            this["autoStartOnLaunch"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrpcConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FrpcConfig}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("common" in $$parsedSource) {
            $$parsedSource["common"] = $$createField6_0($$parsedSource["common"]);
        }
        if ("proxies" in $$parsedSource) {
            $$parsedSource["proxies"] = $$createField7_0($$parsedSource["proxies"]);
        }
        return new FrpcConfig(/** @type {Partial<FrpcConfig>} */($$parsedSource));
    }
}

/**
 * LocalVersion 本地版本信息
 */
export class LocalVersion {
    /**
     * Creates a new LocalVersion instance.
     * @param {Partial<LocalVersion>} [$$source = {}] - The source object to create the LocalVersion.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("installedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["installedAt"] = null;
        }
        if (!("isActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalVersion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalVersion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalVersion(/** @type {Partial<LocalVersion>} */($$parsedSource));
    }
}

/**
 * LogEntry 日志条目
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * ProcessState 进程状态
 */
export class ProcessState {
    /**
     * Creates a new ProcessState instance.
     * @param {Partial<ProcessState>} [$$source = {}] - The source object to create the ProcessState.
     */
    constructor($$source = {}) {
        if (!("configId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * running, stopped, error
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | undefined}
             */
            this["startedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | undefined}
             */
            this["stoppedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["exitCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["exitMessage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 代理状态信息（新增）
             * @member
             * @type {ProxyStatus[] | undefined}
             */
            this["proxies"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 总入流量(字节)
             * @member
             * @type {number | undefined}
             */
            this["totalTrafficIn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 总出流量(字节)
             * @member
             * @type {number | undefined}
             */
            this["totalTrafficOut"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 当前入速度(字节/秒)
             * @member
             * @type {number | undefined}
             */
            this["currentSpeedIn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 当前出速度(字节/秒)
             * @member
             * @type {number | undefined}
             */
            this["currentSpeedOut"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessState}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("proxies" in $$parsedSource) {
            $$parsedSource["proxies"] = $$createField7_0($$parsedSource["proxies"]);
        }
        return new ProcessState(/** @type {Partial<ProcessState>} */($$parsedSource));
    }
}

/**
 * ProxyConfig 代理配置
 * 参考: https://gofrp.org/zh-cn/docs/proxy/
 */
export class ProxyConfig {
    /**
     * Creates a new ProxyConfig instance.
     * @param {Partial<ProxyConfig>} [$$source = {}] - The source object to create the ProxyConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * tcp, udp, http, https, stcp, sudp, xtcp, xudp, tcpmux
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("localIP" in $$source)) {
            /**
             * 本地 IP
             * @member
             * @type {string}
             */
            this["localIP"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * 本地端口
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("remotePort" in $$source)) {
            /**
             * 远程端口（TCP/UDP 类型需要）
             * @member
             * @type {number}
             */
            this["remotePort"] = 0;
        }
        if (!("customDomains" in $$source)) {
            /**
             * 自定义域名（HTTP/HTTPS 类型）
             * @member
             * @type {string[]}
             */
            this["customDomains"] = [];
        }
        if (!("subdomain" in $$source)) {
            /**
             * 子域名（HTTP/HTTPS 类型）
             * @member
             * @type {string}
             */
            this["subdomain"] = "";
        }
        if (!("sk" in $$source)) {
            /**
             * 访问密钥（STCP/SUDP 类型）
             * @member
             * @type {string}
             */
            this["sk"] = "";
        }
        if (!("hostHeaderRewrite" in $$source)) {
            /**
             * 重写 Host 头（HTTP 类型）
             * @member
             * @type {string}
             */
            this["hostHeaderRewrite"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * 自定义请求头（HTTP 类型）
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["headers"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyConfig}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("customDomains" in $$parsedSource) {
            $$parsedSource["customDomains"] = $$createField5_0($$parsedSource["customDomains"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField9_0($$parsedSource["headers"]);
        }
        return new ProxyConfig(/** @type {Partial<ProxyConfig>} */($$parsedSource));
    }
}

/**
 * ProxyStatus 代理状态
 */
export class ProxyStatus {
    /**
     * Creates a new ProxyStatus instance.
     * @param {Partial<ProxyStatus>} [$$source = {}] - The source object to create the ProxyStatus.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("localAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localAddr"] = "";
        }
        if (!("remoteAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteAddr"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * running, offline, error
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("todayTrafficIn" in $$source)) {
            /**
             * 今日入流量(字节)
             * @member
             * @type {number}
             */
            this["todayTrafficIn"] = 0;
        }
        if (!("todayTrafficOut" in $$source)) {
            /**
             * 今日出流量(字节)
             * @member
             * @type {number}
             */
            this["todayTrafficOut"] = 0;
        }
        if (!("currentSpeedIn" in $$source)) {
            /**
             * 当前入速度(字节/秒)
             * @member
             * @type {number}
             */
            this["currentSpeedIn"] = 0;
        }
        if (!("currentSpeedOut" in $$source)) {
            /**
             * 当前出速度(字节/秒)
             * @member
             * @type {number}
             */
            this["currentSpeedOut"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyStatus(/** @type {Partial<ProxyStatus>} */($$parsedSource));
    }
}

/**
 * Settings 应用设置
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * 主题设置: light, dark, system
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * 语言设置: zh-CN, en-US
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("autoRestart" in $$source)) {
            /**
             * 自动重启
             * @member
             * @type {boolean}
             */
            this["autoRestart"] = false;
        }
        if (!("autoStart" in $$source)) {
            /**
             * 开机自启
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("minimizeToTray" in $$source)) {
            /**
             * 最小化到托盘
             * @member
             * @type {boolean}
             */
            this["minimizeToTray"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * VersionInfo 版本信息
 */
export class VersionInfo {
    /**
     * Creates a new VersionInfo instance.
     * @param {Partial<VersionInfo>} [$$source = {}] - The source object to create the VersionInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("releaseDate" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["releaseDate"] = null;
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("checksum" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checksum"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("isLocal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLocal"] = false;
        }
        if (!("isActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo(/** @type {Partial<VersionInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CommonSection.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = ProxyConfig.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ProxyStatus.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
