// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Manager 开机启动管理器
 */
export class Manager {
    /**
     * Creates a new Manager instance.
     * @param {Partial<Manager>} [$$source = {}] - The source object to create the Manager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager(/** @type {Partial<Manager>} */($$parsedSource));
    }
}
