// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ValidationResult 验证结果
 */
export class ValidationResult {
    /**
     * Creates a new ValidationResult instance.
     * @param {Partial<ValidationResult>} [$$source = {}] - The source object to create the ValidationResult.
     */
    constructor($$source = {}) {
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValidationResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField1_0($$parsedSource["errors"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new ValidationResult(/** @type {Partial<ValidationResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
