// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是主应用服务，提供所有 API 绑定
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../platform/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as startup$0 from "../startup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../pkg/types/models.js";

/**
 * AppClearLogs 清除应用日志
 * @returns {$CancellablePromise<void>}
 */
export function AppClearLogs() {
    return $Call.ByID(1765895115);
}

/**
 * AppGetLogs 获取应用日志
 * @param {number} limit
 * @returns {$CancellablePromise<(types$0.LogEntry | null)[]>}
 */
export function AppGetLogs(limit) {
    return $Call.ByID(1992837930, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ConfigDelete 删除配置
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ConfigDelete(id) {
    return $Call.ByID(3456378205, id);
}

/**
 * ConfigExport 导出配置文件
 * @param {string} id
 * @param {string} format
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function ConfigExport(id, format) {
    return $Call.ByID(33845632, id, format).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ConfigGet 获取配置详情
 * @param {string} id
 * @returns {$CancellablePromise<types$0.FrpcConfig | null>}
 */
export function ConfigGet(id) {
    return $Call.ByID(661915534, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ConfigImport 导入配置文件
 * @param {string} name
 * @param {string} data
 * @param {string} format
 * @returns {$CancellablePromise<types$0.FrpcConfig | null>}
 */
export function ConfigImport(name, data, format) {
    return $Call.ByID(39924127, name, data, format).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ConfigList 获取配置列表
 * @returns {$CancellablePromise<(types$0.ConfigMeta | null)[]>}
 */
export function ConfigList() {
    return $Call.ByID(1405867294).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ConfigNew 创建新配置
 * @param {string} name
 * @returns {$CancellablePromise<types$0.FrpcConfig | null>}
 */
export function ConfigNew(name) {
    return $Call.ByID(271078700, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ConfigParse 从源码解析配置
 * @param {string} source
 * @param {string} format
 * @returns {$CancellablePromise<types$0.FrpcConfig | null>}
 */
export function ConfigParse(source, format) {
    return $Call.ByID(2823388485, source, format).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ConfigSave 保存配置
 * @param {string} configJSON
 * @returns {$CancellablePromise<void>}
 */
export function ConfigSave(configJSON) {
    return $Call.ByID(2132024367, configJSON);
}

/**
 * ConfigSerialize 序列化配置到指定格式
 * @param {string} configJSON
 * @param {string} format
 * @returns {$CancellablePromise<string>}
 */
export function ConfigSerialize(configJSON, format) {
    return $Call.ByID(6324848, configJSON, format);
}

/**
 * ConfigValidate 验证配置
 * @param {string} configJSON
 * @returns {$CancellablePromise<config$0.ValidationResult | null>}
 */
export function ConfigValidate(configJSON) {
    return $Call.ByID(3735791740, configJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * FrpcClearLogs 清除进程日志
 * @param {string} configID
 * @returns {$CancellablePromise<void>}
 */
export function FrpcClearLogs(configID) {
    return $Call.ByID(1513255553, configID);
}

/**
 * FrpcGetAllStatus 获取所有进程状态
 * @returns {$CancellablePromise<{ [_ in string]?: types$0.ProcessState | null }>}
 */
export function FrpcGetAllStatus() {
    return $Call.ByID(2259036732).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * FrpcGetLogs 获取进程日志
 * @param {string} configID
 * @param {number} limit
 * @returns {$CancellablePromise<(types$0.LogEntry | null)[]>}
 */
export function FrpcGetLogs(configID, limit) {
    return $Call.ByID(2791614092, configID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * FrpcGetStatus 获取进程状态
 * @param {string} configID
 * @returns {$CancellablePromise<types$0.ProcessState | null>}
 */
export function FrpcGetStatus(configID) {
    return $Call.ByID(2616854849, configID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * FrpcRestart 重启 frpc 进程
 * @param {string} configID
 * @returns {$CancellablePromise<void>}
 */
export function FrpcRestart(configID) {
    return $Call.ByID(3268727532, configID);
}

/**
 * FrpcStart 启动 frpc 进程
 * @param {string} configID
 * @returns {$CancellablePromise<void>}
 */
export function FrpcStart(configID) {
    return $Call.ByID(2746981855, configID);
}

/**
 * FrpcStop 停止 frpc 进程
 * @param {string} configID
 * @returns {$CancellablePromise<void>}
 */
export function FrpcStop(configID) {
    return $Call.ByID(1367592421, configID);
}

/**
 * GetAutoStart 获取开机启动状态
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoStart() {
    return $Call.ByID(3703469645);
}

/**
 * GetDB 获取数据库连接
 * @returns {$CancellablePromise<sql$0.DB | null>}
 */
export function GetDB() {
    return $Call.ByID(1514099786).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetDataDir 获取应用数据目录
 * @returns {$CancellablePromise<string>}
 */
export function GetDataDir() {
    return $Call.ByID(1401830911);
}

/**
 * GetSettings 获取应用设置
 * @returns {$CancellablePromise<types$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(3095130957).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * Greet 示例 API - 返回问候语
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(1761762237, name);
}

/**
 * InitStartupManager 初始化开机启动管理器
 * @param {startup$0.Manager | null} manager
 * @returns {$CancellablePromise<void>}
 */
export function InitStartupManager(manager) {
    return $Call.ByID(235658554, manager);
}

/**
 * Name 返回服务名称
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(2240412479);
}

/**
 * OnShutdown 应用关闭时调用
 * @returns {$CancellablePromise<void>}
 */
export function OnShutdown() {
    return $Call.ByID(3395480963);
}

/**
 * PlatformGetInfo 获取平台信息
 * @returns {$CancellablePromise<platform$0.Info | null>}
 */
export function PlatformGetInfo() {
    return $Call.ByID(914761625).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * SaveSettings 保存应用设置
 * @param {string} settingsJSON
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settingsJSON) {
    return $Call.ByID(1057581132, settingsJSON);
}

/**
 * SetAutoStart 设置开机启动
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoStart(enabled) {
    return $Call.ByID(2438177081, enabled);
}

/**
 * VersionDelete 删除本地版本
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function VersionDelete(version) {
    return $Call.ByID(1814670723, version);
}

/**
 * VersionDownload 下载指定版本
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function VersionDownload(version) {
    return $Call.ByID(1139118408, version);
}

/**
 * VersionGetActive 获取当前活动版本
 * @returns {$CancellablePromise<string>}
 */
export function VersionGetActive() {
    return $Call.ByID(1825375238);
}

/**
 * VersionGetActiveFrpcPath 获取活动版本的 frpc 路径
 * @returns {$CancellablePromise<string>}
 */
export function VersionGetActiveFrpcPath() {
    return $Call.ByID(2039325252);
}

/**
 * VersionListLocal 获取本地已安装版本列表
 * @returns {$CancellablePromise<(types$0.LocalVersion | null)[]>}
 */
export function VersionListLocal() {
    return $Call.ByID(2865641403).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * VersionListRemote 获取远程版本列表
 * @returns {$CancellablePromise<(types$0.VersionInfo | null)[]>}
 */
export function VersionListRemote() {
    return $Call.ByID(2478461494).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * VersionSetActive 设置活动版本
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function VersionSetActive(version) {
    return $Call.ByID(3595282226, version);
}

// Private type creation functions
const $$createType0 = types$0.LogEntry.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = types$0.FrpcConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = types$0.ConfigMeta.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = config$0.ValidationResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = types$0.ProcessState.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Map($Create.Any, $$createType12);
const $$createType14 = sql$0.DB.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = types$0.Settings.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = platform$0.Info.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = types$0.LocalVersion.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = types$0.VersionInfo.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $Create.Array($$createType24);
